# Chương 2: Giải số hệ phương trình tuyến tính A x = b

In [ ]:
from scipy import array
from scipy import random
import scipy.linalg as la
from time import time

for i in range(1,10):
    n = i * 1000
    A = random.rand(n,n)
    b = random.rand(n,1)

    tic = time()
    x = la.solve(A,b)
    toc = time()

    #print(x)
    print('processing time is: ',toc-tic,' sec. (second)')

    
   

# Số điều kiện (Condition number)

In [ ]:
from numpy import array
import numpy.linalg as la
from scipy import random

A = array([[1, 1],[1, 1.001]])
print('A is: ')
print(A)
b = random.rand(2,1)
x = la.solve(A,b)
print('x is: ')
print(x)

A = array([[1, 1],[1, 1.0001]])
print('A is: ')
print(A)
b = random.rand(2,1)
x = la.solve(A,b)
print('x is: ')
print(x)

print(1+4+9+16+25)

In [ ]:
from numpy import array
import numpy.linalg as la

A = array([[1, -2, 3],[-4, 5, -6],[7, -8, 10]])
print(A)

print('The 1-norm of A is: ',la.norm(A,1))

print('The Euclidean/2/Frobenius-norm of A is: ',la.norm(A,2))

import numpy as np
print('The infinity-norm of A is: ',la.norm(A,np.inf))


In [ ]:
from numpy import array
import numpy.linalg as la
from scipy.linalg import hilbert

A = array([[1, -2, 3],[-4, 5, -6],[7, -8, 10]])
print('A is: ')
print(A)
cond_A = la.cond(A)
print('Condition number of A is: ',cond_A)

# Hilbert Matrix
B = hilbert(3)
print('B is: ')
print(B)
cond_B = la.cond(B)
print('Condition number of B is: ', cond_B)

# Phép khử Gauss và phân tích LU (Gaussian Elimination & LU Decomposition)

In [ ]:
L, U = lu(A,True)

print(L)
print(U)

from numpy import dot
dot(L,U)-A

In [ ]:
from scipy.linalg import lu
from numpy import array

A = array([[10,-1,2,-3],[1,10,-1,2],[2,3,20,-1],[3,2,1,20]])
print(A)

P, L, U = lu(A)
print("Ma tran P")
print(P)
print("Ma tran L")
print(L)
print("Ma tran U")
print(U)

#print(P*L*U - A)   # Matlab thi duoc, Python thi 0
print(dot(P,dot(L,U)) - A) # Dung trong Python

In [1]:
from scipy.linalg import lu
from numpy import array, dot

A = array([[1,2,3],[4,5,6],[-7,-8,0]])

print(A)

P, L, U = lu(A)
print("Ma tran P")
print(P)
print("Ma tran L")
print(L)
print("Ma tran U")
print(U)

print(dot(P,dot(L,U)) - A) # Dung trong Python

[[ 1  2  3]
 [ 4  5  6]
 [-7 -8  0]]
Ma tran P
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Ma tran L
[[ 1.          0.          0.        ]
 [-0.14285714  1.          0.        ]
 [-0.57142857  0.5         1.        ]]
Ma tran U
[[-7.         -8.          0.        ]
 [ 0.          0.85714286  3.        ]
 [ 0.          0.          4.5       ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
from numpy import array
import numpy.linalg as la

A = array([[1, -2, 3],[-4, 5, -6],[7, -8, 10]])
print(A)

L = la.cholesky(A.T@A)
print(L)

# Iterative methods: Jacobi, Gauss-Seidel

In [ ]:
from numpy import array, dot
import numpy.linalg as la

A = array([[3,1, 1],[1, 5, 2],[1, 8, 10]])

b = array([5,8,19])

P =  array([[3, 0, 0],[0, 5, 0],[0, 0, 10]])
N = A - P
ivP = inv(P)
x0 = array([0,0,0]); xold = x0;

for i in range(1,100):
    xnew = inv(P) * (-N*xold+b)
    
print(xnew)


# Least square - Over/Under-determined systems

In [ ]:
print("Cach 1: phuong trinh chinh tac")
M = dot(A.T,A)
print(M)
n = dot(A.T,b)
print(n)
from numpy.linalg import solve


In [ ]:
print("Cach 2: su dung phan tich QR")
from scipy.linalg import qr
Q,R = qr(A)
#print(Q)
#print(R)
#print(dot(Q,R)-A)

Q1 = Q[:,0:2]
R1 = R[0:2,:]
print(Q1)
print(R1)
print(dot(Q1,R1)-A)

p = dot(Q1.T,b)
print(p)

from numpy.linalg import solve
x = solve(R1,p)
print(x)