# Why numerical analysis is needed? 
# Why (theoretical) analysis is not enough?

# Example 1. Computing integral (from Prof. Ky Anh's book)

In [10]:
# Computing the integral 
# Using recursion        I_n = 1 - n * I_{n-1} ;  I_0 = 1/e
                         
                        # I_new = 1 - n * I_old 
                        # I_old = I_newI_n = int_0^1 x^n e^{x-1}dx (n>=1) 
            
# I_200 = 1 - 200 * I_199
# I_199 = 1 - 199 * I_198

# numpy, scipy, matplotlib, mayavi
# tensorflow, pandas, keras, scikit-learn

from numpy import exp

e = exp(1)
I_old = 1/e   # This is I_{n-1}

# Dem tu 0 nhu C => range(n+1) = 0, 1, 2, ..., n
                  # arange(1,n+1,2) = 1,3,5, ...

n = 19;                       # Notice the switch of sign - Chú ý thay đổi dấu khi n chẵn/lẻ

for i in range(n+1):          # i = 0,1,2, ..., n = 19
    I_new = 1 - i * I_old          # Notice about the loop - Chú ý vòng lặp 0 có end
                                 # Chú ý thụt đầu dòng sai là đứt ngay
    I_old = I_new

print(I_new)        # Keep in mind the indent - Chú ý việc thụt đầu dòng

-4.47507315596451e+16


In [7]:
# integration is not always possible theoretically
# help(integrate.quad)

# Computing the integral I_n = int_0^1 x^n e^{x-1}dx (n>=1)


from numpy import exp, sqrt
from scipy import integrate

n = 100; 

# f(x) = x^n * e^{x-1} 
fx = lambda x : x**n * exp(x-1)                 # Viết hàm tạm thời kiểu lambda

value, error = integrate.quad(fx, 0, 1)

print('The result is: ',value)
print('The absolute error is: ',error)

The result is:  0.009804855005376046
The absolute error is:  1.5644972679651507e-14


In [8]:
def f(x):
    from numpy import sqrt
    p = 3;
    return sqrt(x**p + 1)

print(f(2))


g = lambda x : sqrt(x**3 + 1)

print(g(2))

3.0
3.0


# Example 2. Inverse matrix undered perturbation

In [5]:
# Perturbation may cause serious troubles

import numpy as np
from numpy.linalg import inv , cond  # linalg = linear algebra 

A = np.array([[1, 1],[1, 1.01]])

#  A = 
#      1  1
#      1  1.01 

print(inv(A))

B = np.array([[1, 1],[1, 1.001]])
print(inv(B))

print(cond(B))

from numpy import dot

b = np.array([1.1,0])

print(dot(inv(B),b))


[[ 101. -100.]
 [-100.  100.]]
[[ 1001. -1000.]
 [-1000.  1000.]]
4002.000750125414
[ 1101.1 -1100. ]


# Example 4. Hilbert matrix of very big size

In [6]:
import scipy.linalg as la

n = 3
A = la.hilbert(n)
print('A is: ',A)
print('inv(A) is: ',la.inv(A))
print('Determinant of A is: ',la.det(A))

n = 100
A = la.hilbert(n)
print('A is: ')
print(A)
print('inv(A) is: ')
print(la.inv(A))

# Lets guess det(A) if n = 100?
print('Determinant of A is: ',la.det(A))


A is:  [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
inv(A) is:  [[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]
Determinant of A is:  0.00046296296296296125
A is: 
[[1.         0.5        0.33333333 ... 0.01020408 0.01010101 0.01      ]
 [0.5        0.33333333 0.25       ... 0.01010101 0.01       0.00990099]
 [0.33333333 0.25       0.2        ... 0.01       0.00990099 0.00980392]
 ...
 [0.01020408 0.01010101 0.01       ... 0.00512821 0.00510204 0.00507614]
 [0.01010101 0.01       0.00990099 ... 0.00510204 0.00507614 0.00505051]
 [0.01       0.00990099 0.00980392 ... 0.00507614 0.00505051 0.00502513]]
inv(A) is: 
[[ 1.65712222e+02 -1.38147870e+04  3.76939585e+05 ... -1.72810788e+09
   1.97037986e+09 -5.00210147e+08]
 [-1.38704556e+04  1.57688052e+06 -4.95660558e+07 ...  3.20304231e+11
  -3.64476472e+11  8.70374865e+10]
 [ 3.81045997e+05 -4.98682171e+07  1.71111434e+09 ... -1.42361380e+13
   1.63196662e+13 -3