In [ ]:
import numpy as np
from numpy.linalg import qr,solve
from numpy import array, dot

ep = 1e-12;

A = array([[1, ep, 0], [1, 0, ep]]).T
#print('A = \n',A)

b = array([1,2,3])
#print('b = \n',b)

M = np.dot(A.T,A)
#print(M)

n = np.dot(A.T,b)
x = solve(M,n)

In [ ]:
def least_square_qr(A,b):  
    import numpy.linalg as la
    Q, R = la.qr(A)
    #print('Q = \n',Q)
    #print('R = \n',R)

    x = la.solve(R,np.dot(Q.T,b))
    return x



In [29]:
x = np.array([0.2 , 0.3, 0.4])
y = np.array([3.16, 2.38, 1.75])


In [15]:
import numpy as np
import numpy.linalg as la
from numpy.linalg import qr

A = np.array([[1, 1, 1, 1],[0, 0.5, 1, 1.5],[0, 0.25, 1, 2.25]]).T
print('A = \n',A)

Q, R = qr(A)
print('Q = \n',Q)
print('R = \n',R)

gamma = np.array([1.000, 0.994, 0.990, 0.985]).T
b = np.log(gamma)
print('b = ',b)

#print(b.shape)
#print(np.dot(Q.T,b))

x = la.solve(R,np.dot(Q.T,b))
x[-1] = np.exp(x[-1])
print('x = ', x)

A = 
 [[1.   0.   0.  ]
 [1.   0.5  0.25]
 [1.   1.   1.  ]
 [1.   1.5  2.25]]
Q = 
 [[-0.5         0.67082039  0.5       ]
 [-0.5         0.2236068  -0.5       ]
 [-0.5        -0.2236068  -0.5       ]
 [-0.5        -0.67082039  0.5       ]]
R = 
 [[-2.         -1.5        -1.75      ]
 [ 0.         -1.11803399 -1.67705098]
 [ 0.          0.          0.5       ]]
b =  [ 0.         -0.00601807 -0.01005034 -0.01511364]
x =  [-1.50842361e-04 -1.13067909e-02  1.00095523e+00]
