In [16]:
def newton(f,df,x0,nmax,epsilon):
    x1 = x0
    for n in range(0,nmax):
        fx1 = f(x1)
        if abs(fx1) < epsilon:
            print('Tim duoc nghiem sau',n,'lan lap.')
            return x1
        Df = df(x1)
        if Df == 0:
            print('Khong tim thay nghiem vi dao ham = 0')
            return None
        x1 = x1 - fx1/Df                
    print('Vuot qua so lan lap, khong tim thay nghiem.')
    return None

# Test code
x0,nmax,epsilon = (1,10,1e-10)
f = lambda x: x**3 - x**2 - 1
df = lambda x: 3*x**2 - 2*x
approx = newton(f,df,x0,nmax,epsilon)
print(approx)

Tim duoc nghiem sau 6 lan lap.
1.4655712318767877


In [17]:
f = lambda x: x**(1/3)
df = lambda x: (1/3)*x**(-2/3)
approx = newton(f,df,0.1,100,1e-2)
print(approx)

Vuot qua so lan lap, khong tim thay nghiem.
None


In [12]:
import numpy as np
A = np.array([[1,2,3],[0, 2, 0],[0, 0, 3]])
b = np.array([1,2,3])
print(A/b)

[[1. 1. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
import numpy as np

def Newton_system(F, J, x, nmax, eps):
    """
    Solve nonlinear system F=0 by Newton's method.
    J is the Jacobian of F. Both F and J must be functions of x.
    At input, x holds the start value. The iteration continues
    until ||F|| < eps.
    """
    F_value = F(x)
    F_norm = np.linalg.norm(F_value, ord=2)  # l2 norm of vector
    iteration_counter = 0
    while abs(F_norm) > eps and iteration_counter < nmax:
        delta = np.linalg.solve(J(x), -F_value)
        x = x + delta
        F_value = F(x)
        F_norm = np.linalg.norm(F_value, ord=2)
        iteration_counter += 1

    # Here, either a solution is found, or too many iterations
    if abs(F_norm) > eps:
        iteration_counter = -1
    return x, iteration_counter

# Test code
f = lambda x: x**3 - x**2 - 1
df = lambda x: 3*x**2 - 2*x
approx = newton(f,df,1,100,1e-10)
print(approx)        



Found solution after 6 iterations.
1.4655712318767877


In [23]:
def newton(f,df,x0,nmax,eps):
    n = 0;
    while (abs(f(x0))>eps) and (n<nmax):
        x1 = x0 - f(x0)/df(x0);
        x0 = x1;
        n += 1;
    return x0, n

# Test ham newton vua viet
x0,nmax,eps = (0.5,100,1e-6);
def f(x): return x**4-3*x**2+75*x-10000
def df(x): return 4*x**3-6*x+75
#f = lambda x: x**2
#df = lambda x: 2*x

x0, n = newton(f,df,x0,nmax,eps)
print(x0)
print(n)


9.886002701149666
14


In [24]:
import numpy as np
from numpy import exp, sin, cos, log

x0,nmax,eps = (1.5,100,1e-5);
def f(x): return exp(x) + 2**(-x) + 2 * cos(x) - 6
def df(x): return exp(x) - 2**(-x) * log(2) - 2 * sin(x)

x1, n = newton(f,df,x0,nmax,eps)
print(x0)
print(n)

1.5
4


In [15]:
def can_bac_2(a,x0,nmax,eps):
    n = 0;
    def f(x): return x**2-a
    while (n<nmax) and (abs(f(x0))>eps):
        x1 = x0 - (x0**2-a)/(2*x0);
        x0 = x1;        
        n += 1
    return x1, n

x0,nmax,eps = (1e-7,100,1e-10);
a = 1;
x1, n = can_bac_2(a,x0,nmax,eps)
print(x1)
print(n)


1.0000000000043956
27


In [17]:
def bai3(a,b,x0,nmax,tol):    
    
    fx = a * x0 + b;
    x1 = x0 - fx/a;
    n = 0;
    while (n<nmax) and (abs(x1-x0)>tol):
        x0 = x1;
        fx = a * x0 + b;
        x1 = x0 - fx/a;
        n += 1
    if n==nmax-1:
            print("Co the khong co nghiem = Newton hoac nmax qua be")                
    return x1, n

# Test
a,b,x0,nmax,tol = (0.1,0.5,0,300,1e-6);
x0, n = bai3(a,b,x0,nmax,tol)
print("No la --- ",x0)
print("So lan lap la ----",n)


No la ---  -5.0
So lan lap la ---- 1
