In [ ]:
#Function
def generateSquare(n): 
    # 2-D array with all  
    # slots set to 0 
    magicSquare = [[0 for x in range(n)] 
                      for y in range(n)] 
    # initialize position of 1 
    i = n / 2
    j = n - 1
    # Fill the square by placing values 
    num = 1
    while num <= (n * n): 
        if i == -1 and j == n: # 3rd condition 
            j = n - 2
            i = 0
        else:  
            # next number goes out of 
            # right side of square  
            if j == n: 
                j = 0    
            # next number goes  
            # out of upper side 
            if i < 0: 
                i = n - 1
        if magicSquare[int(i)][int(j)]: # 2nd condition 
            j = j - 2
            i = i + 1
            continue
        else: 
            magicSquare[int(i)][int(j)] = num 
            num = num + 1
        j = j + 1
        i = i - 1 # 1st condition 
    # Printing the square 
    print ("Magic Square for n =", n) 
    print ("Sum of each row or column",n * (n * n + 1) / 2, "\n") 
    for i in range(0, n): 
        for j in range(0, n): 
            print('%2d ' % (magicSquare[i][j]),end = '') 
            # To display output  
            # in matrix form 
            if j == n - 1:  
                print()
# Driver Code 
# Works only when n is odd 
n=int(input("Number of rows of the Magic Square:"))
generateSquare(n)

In [ ]:
with open('Midterm_K65.txt', 'w') as f:
    f.write('Midterm_K65')

In [17]:
import numpy as np
import numpy.linalg as la

A = generateSquare(3)

Magic Square for n = 3
Sum of each row or column 15.0 

 2  7  6 
 9  5  1 
 4  3  8 


In [ ]:
type(A)

In [ ]:
A = np.array(A)
A = np.reshape(A,(11,11))
help(np.reshape)

In [24]:
A = np.array([[2,7,6],[9,5,1],[4,3,8]])
H = A@A.T
L = la.cholesky(H)
print("H = \n ",H)
b = np.array([18, 2, 85])
x = la.solve(A,b)
print("x = ",x)

H = 
  [[ 89  59  77]
 [ 59 107  59]
 [ 77  59  89]]
x =  [ 3.79166667 -8.83333333 12.04166667]


In [28]:
H = np.array([[89,59,77], [59,107,59], [77,59,89]])
print(H)

[[ 89  59  77]
 [ 59 107  59]
 [ 77  59  89]]
