In [2]:
# Import package that used in the assigment
import numpy as np
import scipy.linalg as linalg

# Câu 1

In [1]:
def generate_matrix(t):
    """
    Args:
        t: represent to value t in matrix [[1, t], [t, 1+t^2]]
    Returns:
        matrix: a matrix corresponding to input
    """
    
    matrix = [[1, t], [t, 1 + t**2]]
    
    return np.array(matrix)

In [3]:
start = 100
end = 1000
step = 100

for t in range(start, end+1, step):
    # Take matrix
    matrix = generate_matrix(t)
    
    # Calculate norm 1, 2, infty
    norm1 = np.linalg.norm(matrix, ord=1)
    norm2 = np.linalg.norm(matrix, ord=2)
    normInfty = np.linalg.norm(matrix, ord=np.inf)
    
    # Calculate conditioning
    conditioning = np.linalg.cond(matrix)
    
    # print
    print(f"t = {t} \nMatrix: \n{matrix} \nConditioning: {conditioning}")
    print(f"Norm 1: {norm1}\nNorm 2: {norm2}\nNorm Infinity: {normInfty}\n\n")

t = 100 
Matrix: 
[[    1   100]
 [  100 10001]] 
Conditioning: 100040002.01832864
Norm 1: 10101.0
Norm 2: 10001.999900019997
Norm Infinity: 10101.0


t = 200 
Matrix: 
[[    1   200]
 [  200 40001]] 
Conditioning: 1600159998.9022539
Norm 1: 40201.0
Norm 2: 40001.99997500125
Norm Infinity: 40201.0


t = 300 
Matrix: 
[[    1   300]
 [  300 90001]] 
Conditioning: 8100360088.874936
Norm 1: 90301.0
Norm 2: 90001.99998888916
Norm Infinity: 90301.0


t = 400 
Matrix: 
[[     1    400]
 [   400 160001]] 
Conditioning: 25600640179.182945
Norm 1: 160401.0
Norm 2: 160001.99999375007
Norm Infinity: 160401.0


t = 500 
Matrix: 
[[     1    500]
 [   500 250001]] 
Conditioning: 62501002664.4103
Norm 1: 250501.0
Norm 2: 250001.9999960001
Norm Infinity: 250501.0


t = 600 
Matrix: 
[[     1    600]
 [   600 360001]] 
Conditioning: 129601433531.76285
Norm 1: 360601.0
Norm 2: 360001.99999722216
Norm Infinity: 360601.0


t = 700 
Matrix: 
[[     1    700]
 [   700 490001]] 
Conditioning: 240101964703.0

# Câu 2

In [ ]:
def hermit_matrix(n):
    """
    Args:
        n: degree of hermit matrix
    Output:
        matrix: hermit matrix that corresponding to n
    """
    
    # Create zero matrix with dimensions nxn
    matrix = np.zeros((n, n))
    
    # Update value in hermit matrix
    for row in range(n):
        for col in range(n):
            matrix[row, col] = (1 / (row + col + 1)) ** n
    
    return matrix

In [ ]:
# Test function
hermit5 = hermit_matrix(5)
hermit12 = hermit_matrix(12)

# Calculte norm
matrix_list = [hermit5, hermit12]
# Loop and calculate
for matrix in matrix_list:
    
    # Calculate norm 1, 2, infty
    norm1 = np.linalg.norm(matrix, ord=1)
    norm2 = np.linalg.norm(matrix, ord=2)
    normInfty = np.linalg.norm(matrix, ord=np.inf)
    
    # Calculate conditioning
    conditioning = np.linalg.cond(matrix)
    
    # print
    print(f"Matrix: \n{matrix} \nConditioning: {conditioning}")
    print(f"Norm 1: {norm1}\nNorm 2: {norm2}\nNorm Infinity: {normInfty}\n\n")

Matrix: 
[[1.00000000e+00 3.12500000e-02 4.11522634e-03 9.76562500e-04
  3.20000000e-04]
 [3.12500000e-02 4.11522634e-03 9.76562500e-04 3.20000000e-04
  1.28600823e-04]
 [4.11522634e-03 9.76562500e-04 3.20000000e-04 1.28600823e-04
  5.94990183e-05]
 [9.76562500e-04 3.20000000e-04 1.28600823e-04 5.94990183e-05
  3.05175781e-05]
 [3.20000000e-04 1.28600823e-04 5.94990183e-05 3.05175781e-05
  1.69350878e-05]] 
Conditioning: 17430610.959620513
Norm 1: 1.0366617888374487
Norm 2: 1.0009978712498357
Norm Infinity: 1.0366617888374487


Matrix: 
[[1.00000000e+00 2.44140625e-04 1.88167642e-06 5.96046448e-08
  4.09600000e-09 4.59393658e-10 7.22476158e-11 1.45519152e-11
  3.54070616e-12 1.00000000e-12 3.18630818e-13 1.12156655e-13]
 [2.44140625e-04 1.88167642e-06 5.96046448e-08 4.09600000e-09
  4.59393658e-10 7.22476158e-11 1.45519152e-11 3.54070616e-12
  1.00000000e-12 3.18630818e-13 1.12156655e-13 4.29219824e-14]
 [1.88167642e-06 5.96046448e-08 4.09600000e-09 4.59393658e-10
  7.22476158e-11 1.45

# Câu 3

a) Hãy sử dụng phương pháp khử Gauss trong lý thuyết để tìm phân tích LU
và giải hệ phương trình sau

\begin{align*}
    2x_1 + 4x_2 + 3x_3 &= 3 \\
    3x_1 + x_2 - 2x_3 &= 3 \\
    4x_1 + 11x_2 + 7x_3 &= 4
\end{align*}

Ta có: 

$$
A
=
\begin{bmatrix}
2 & 4 & 3 & 3  \\
3 & 1 & -2 & 3  \\
4 & 11 & 7 & 4 
\end{bmatrix}
$$

$
H_2 = H_2 - \frac32 H_1 \
H_3 = H_3 - 2H_1
$

$$
=
\begin{bmatrix}
2 & 4 & 3 & 3  \\
0 & -5 & -\frac{13}{2} & -\frac32  \\
0 & 3 & 1 & -2 
\end{bmatrix}
$$

$H_3 = H_3 + \frac35 H_2$

$$
=
\begin{bmatrix}
2 & 4 & 3 & 3  \\
0 & -5 & -\frac{13}{2} & -\frac32  \\
0 & 0 & -\frac{29}{10} & -\frac{29}{10}
\end{bmatrix}
$$

$\Rightarrow x_3=1, x_2=-1, x_1=2$

$$
L_1 = 
\begin{bmatrix}
1 & 0 & 0   \\
-\frac32 & 1 & 0  \\
-2 & 0 & 1
\end{bmatrix}
$$

$$
L_2 = 
\begin{bmatrix}
1 & 0 & 0   \\
0 & 1 & 0  \\
0 & \frac35 & 1
\end{bmatrix}
$$


$$
L = (L_1 L_2)^{-1}
=
\begin{bmatrix}
1 & 0 & 0   \\
\frac32 & 1 & 0  \\
2 & -\frac35 & 1
\end{bmatrix}
$$

$$
U =
\begin{bmatrix}
2 & 4 & 3  \\
0 & -5 & -\frac{13}{2} \\
0 & 0 & -\frac{29}{10} 
\end{bmatrix}
$$

In [ ]:
# Test
L = [[1, 0, 0], [3 / 2, 1, 0], [2, -3 / 5, 1]]
U = [[2, 4, 3], [0, -5, -13 / 2], [0, 0, -29 / 10]]
L = np.array(L)
U = np.array(U)

np.dot(L, U)

array([[ 2.,  4.,  3.],
       [ 3.,  1., -2.],
       [ 4., 11.,  7.]])

## b

**Thực hành:** Viết hàm trong Python để tìm phân tích $A = LU$ và giải hệ phương trình $Ax = b$ ở trên. So sánh kết quả của các em với cách giải sử dụng toolbox linalg trong Python.

In [ ]:
A = [[2, 4, 3], [3, 1, -2], [4, 11, 7]]
A = np.array(A, dtype=float)
b = [3, 3, 4]

def LUdecomp(A):
    """
    Args:
        A: a nxn matrix
    Return: 
        L: lower triangular matrix
        U: uper triangular matrix
    Note: A = LU
    """
    
    # Initialize L is an unit matrix
    L = np.eye(3)
    n = len(A)
    
    # Loop and use gauss elimation
    for col in range(n-1):
        for row in range(col + 1, n):
            if A[row, col] != 0:
                lam = A[row, col] / A[col, col]
                A[row, col:n] = A[row, col:n] - lam * A[col, col:n]
                L[row, col] = lam
    
    return L, A

L, U = LUdecomp(A)
print(f"L: \n{L} \nU: \n{U}")

def solve(L, U, b):
    """
    Args:
        L: a lower triangle matrix
        U: a upper triangle matrix
        b: a vector
    Return:
        Solution of Ax = b, where A = L * U
    """   
    n = len(L)
    
    # Because A=LU, Ax=b <-> LUx=b. Assign Ux=y, we will solve Ly=b, then Ux=y
    
    # Solve Ly=b
    for idx in range(1, n):
        b[idx] = b[idx] - np.dot(L[idx, 0:idx], b[0:idx])
    
    # Solve Ux = y
    b[n-1] = b[n-1] / U[n-1, n-1]
    for idx in range(n-2, -1, -1):
        b[idx] = (b[idx] - np.dot(U[idx, idx+1:n], b[idx+1 : n])) / U[idx, idx]
    
    return b

solve(L, U, b)

L: 
[[ 1.   0.   0. ]
 [ 1.5  1.   0. ]
 [ 2.  -0.6  1. ]] 
U: 
[[ 2.   4.   3. ]
 [ 0.  -5.  -6.5]
 [ 0.   0.  -2.9]]


[2.0000000000000004, -1.0000000000000004, 1.0000000000000002]

In [ ]:
# Use tool
A = [[2, 4, 3], [3, 1, -2], [4, 11, 7]]
A = np.array(A, dtype=float)
b = [3, 3, 4]
np.linalg.solve(A, b)

array([ 2., -1.,  1.])

# Câu 4

# Câu 5

Tìm hiểu các ma trận Pascal, Leslie và Van der Monde trong module `scipy.linalg`. Tìm các phân tích LU và PLU của chúng, ứng với các ma trận cỡ 3 × 3 hoặc 4 × 4.

## Pascal matrix

In [ ]:
# Pascal Matrix 
pascal3 = linalg.pascal(3)

# LU 
linalg.lu(pascal3, permute_l=True)    # if you decomposite to PLU, change permute_l=False

(array([[1. , 0. , 0. ],
        [1. , 0.5, 1. ],
        [1. , 1. , 0. ]]),
 array([[ 1. ,  1. ,  1. ],
        [ 0. ,  2. ,  5. ],
        [ 0. ,  0. , -0.5]]))

In [ ]:
# Pascal Matrix 
pascal4 = linalg.pascal(4)

# LU 
linalg.lu(pascal4, permute_l=True)    # if you decomposite to PLU, change permute_l=False

(array([[1.        , 0.        , 0.        , 0.        ],
        [1.        , 0.33333333, 1.        , 1.        ],
        [1.        , 0.66666667, 1.        , 0.        ],
        [1.        , 1.        , 0.        , 0.        ]]),
 array([[ 1.        ,  1.        ,  1.        ,  1.        ],
        [ 0.        ,  3.        ,  9.        , 19.        ],
        [ 0.        ,  0.        , -1.        , -3.66666667],
        [ 0.        ,  0.        ,  0.        ,  0.33333333]]))

## Leslie matrix

In [ ]:
# Leslie matrix
leslie3 = linalg.leslie([0.1, 2.0, 1.0], [0.2, 0.8])

# LU 
linalg.lu(leslie3, permute_l=True)    # if you decomposite to PLU, change permute_l=False

(array([[0.5, 1. , 0. ],
        [1. , 0. , 0. ],
        [0. , 0.4, 1. ]]),
 array([[ 0.2,  0. ,  0. ],
        [ 0. ,  2. ,  1. ],
        [ 0. ,  0. , -0.4]]))

In [ ]:
# Leslie matrix
leslie4 = linalg.leslie([0.1, 2.0, 1.0, 0.1], [0.2, 0.8, 0.7])

# LU 
linalg.lu(leslie4, permute_l=True)    # if you decomposite to PLU, change permute_l=False

(array([[ 0.5       ,  1.        ,  0.        ,  0.        ],
        [ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.4       , -0.57142857,  1.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ]]),
 array([[ 0.2 ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  2.  ,  1.  ,  0.1 ],
        [ 0.  ,  0.  ,  0.7 ,  0.  ],
        [ 0.  ,  0.  ,  0.  , -0.04]]))

## Van der Monde matrix 

In [ ]:
# Vandermode matrix
vander3 = np.vander([1, 2, 3])

# LU 
linalg.lu(vander3, permute_l=True)    # if you decomposite to PLU, change permute_l=False

(array([[0.11111111, 1.        , 1.        ],
        [0.44444444, 1.        , 0.        ],
        [1.        , 0.        , 0.        ]]),
 array([[9.        , 3.        , 1.        ],
        [0.        , 0.66666667, 0.55555556],
        [0.        , 0.        , 0.33333333]]))

In [ ]:
# Vandermode matrix
vander4 = np.vander([1, 2, 3, 4])

# LU 
linalg.lu(vander4, permute_l=True)    # if you decomposite to PLU, change permute_l=False

(array([[0.015625  , 0.33333333, 1.        , 0.        ],
        [0.125     , 0.88888889, 0.66666667, 1.        ],
        [0.421875  , 1.        , 0.        , 0.        ],
        [1.        , 0.        , 0.        , 0.        ]]),
 array([[64.        , 16.        ,  4.        ,  1.        ],
        [ 0.        ,  2.25      ,  1.3125    ,  0.578125  ],
        [ 0.        ,  0.        ,  0.5       ,  0.79166667],
        [ 0.        ,  0.        ,  0.        , -0.16666667]]))

# Câu 6

Tìm các phân tích PLU của các ma trận A dưới đây và giải hệ phương trình vi phân tương ứng, với b là random vector, làm tròn 4 chữ số thập phân khi tính toán bằng tay.

(i) $$ 
A = 
\begin{bmatrix}
4 & -1 & -2 \\
-1 & 4 & -1 \\
-1 & -2 & 4
\end{bmatrix}
$$

In [ ]:
# Initialize
A = [[4, -1, -2], [-1, 4, -1], [-1, -2, 4]]
b = np.random.randint(10, size=3)
A = np.array(A)
print(f"Ax' = b, where \nA = {A}, \nb = {b}\n\n")

# PLU decomposition
P, L, U = linalg.lu(A)
print(f"P matrix: \n{P} \nL matrix: \n{L} \nU matrix: \n{U}")

# Solve
LU, pivot = linalg.lu_factor(A) # another presentation of PLU decomposition
print(f"\n\nLU matrix: \n{LU} \npivot: {pivot}")
x = linalg.lu_solve((LU, pivot), b)

# Print
print("\n\nx' = ", np.round(x, 4))

Ax' = b, where 
A = [[ 4 -1 -2]
 [-1  4 -1]
 [-1 -2  4]], 
b = [6 1 2]


P matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
L matrix: 
[[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [-0.25 -0.6   1.  ]] 
U matrix: 
[[ 4.   -1.   -2.  ]
 [ 0.    3.75 -1.5 ]
 [ 0.    0.    2.6 ]]


LU matrix: 
[[ 4.   -1.   -2.  ]
 [-0.25  3.75 -1.5 ]
 [-0.25 -0.6   2.6 ]] 
pivot: [0 1 2]


x' =  [2.8205 1.4359 1.9231]


(ii) $$ 
A = 
\begin{bmatrix}
3 & 1 & -1 \\
-1 & 4 & 1 \\
2 & -1 & 6
\end{bmatrix}
$$

In [ ]:
# Initialize
A = [[3, 1, -1], [-1, 4, 1], [2, -1, 6]]
b = np.random.randint(10, size=3)
A = np.array(A)
print(f"Ax' = b, where \nA = {A}, \nb = {b}\n\n")

# PLU decomposition
P, L, U = linalg.lu(A)
print(f"P matrix: \n{P} \nL matrix: \n{L} \nU matrix: \n{U}")

# Solve
LU, pivot = linalg.lu_factor(A) # another presentation of PLU decomposition
print(f"\n\nLU matrix: \n{LU} \npivot: {pivot}")
x = linalg.lu_solve((LU, pivot), b)

# Print
print("\n\nx' = ", np.round(x, 4))

Ax' = b, where 
A = [[ 3  1 -1]
 [-1  4  1]
 [ 2 -1  6]], 
b = [1 2 6]


P matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
L matrix: 
[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [ 0.66666667 -0.38461538  1.        ]] 
U matrix: 
[[ 3.          1.         -1.        ]
 [ 0.          4.33333333  0.66666667]
 [ 0.          0.          6.92307692]]


LU matrix: 
[[ 3.          1.         -1.        ]
 [-0.33333333  4.33333333  0.66666667]
 [ 0.66666667 -0.38461538  6.92307692]] 
pivot: [0 1 2]


x' =  [0.5 0.4 0.9]


(iii) $$ 
A = 
\begin{bmatrix}
0 & 1 & 0 & 0 \\
2 & 0 & 1 & 0 \\
0 & 2 & 0 & 1 \\
0 & 0 & 2 & 0
\end{bmatrix}
$$

In [ ]:
# Initialize
A = [[0, 1, 0, 0], [2, 0, 1, 0], [0, 2, 0, 1], [0, 0, 2, 0]]
b = np.random.randint(10, size=4)
A = np.array(A)
print(f"Ax' = b, where \nA = {A}, \nb = {b}\n\n")

# PLU decomposition
P, L, U = linalg.lu(A)
print(f"P matrix: \n{P} \nL matrix: \n{L} \nU matrix: \n{U}")

# Solve
LU, pivot = linalg.lu_factor(A) # another presentation of PLU decomposition
print(f"\n\nLU matrix: \n{LU} \npivot: {pivot}")
x = linalg.lu_solve((LU, pivot), b)

# Print
print("\n\nx' = ", np.round(x, 4))

Ax' = b, where 
A = [[0 1 0 0]
 [2 0 1 0]
 [0 2 0 1]
 [0 0 2 0]], 
b = [2 4 3 1]


P matrix: 
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] 
L matrix: 
[[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.5 0.  1. ]] 
U matrix: 
[[ 2.   0.   1.   0. ]
 [ 0.   2.   0.   1. ]
 [ 0.   0.   2.   0. ]
 [ 0.   0.   0.  -0.5]]


LU matrix: 
[[ 2.   0.   1.   0. ]
 [ 0.   2.   0.   1. ]
 [ 0.   0.   2.   0. ]
 [ 0.   0.5  0.  -0.5]] 
pivot: [1 2 3 3]


x' =  [ 1.75  2.    0.5  -1.  ]


(iv) $$ 
A = 
\begin{bmatrix}
2 & 2 & 0 & 0 \\
2 & 2 & 1 & 0 \\
1 & 1 & 0 & 2 \\
0 & 1 & 0 & 0
\end{bmatrix}
$$

In [ ]:
# Initialize
A = [[2, 2, 0, 0], [2, 2, 1, 0], [1, 1, 0, 2], [0, 1, 0, 0]]
b = np.random.randint(10, size=4)
A = np.array(A)
print(f"Ax' = b, where \nA = {A}, \nb = {b}\n\n")

# PLU decomposition
P, L, U = linalg.lu(A)
print(f"P matrix: \n{P} \nL matrix: \n{L} \nU matrix: \n{U}")

# Solve
LU, pivot = linalg.lu_factor(A) # another presentation of PLU decomposition
print(f"\n\nLU matrix: \n{LU} \npivot: {pivot}")
x = linalg.lu_solve((LU, pivot), b)

# Print
print("\n\nx' = ", np.round(x, 4))

Ax' = b, where 
A = [[2 2 0 0]
 [2 2 1 0]
 [1 1 0 2]
 [0 1 0 0]], 
b = [8 7 7 8]


P matrix: 
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]] 
L matrix: 
[[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [1.  0.  1.  0. ]
 [0.5 0.  0.  1. ]] 
U matrix: 
[[2. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 2.]]


LU matrix: 
[[2.  2.  0.  0. ]
 [0.  1.  0.  0. ]
 [1.  0.  1.  0. ]
 [0.5 0.  0.  2. ]] 
pivot: [0 3 3 3]


x' =  [-4.   8.  -1.   1.5]


# Câu 7

Trong trường hợp ma trận A là đối xứng, xác định dương thì phương pháp Cholesky thường được sử dụng. Hãy đọc phương pháp này trang 116-120 (Giáo trình ĐHBK) hoặc Section 2.4 (Giáo trình Kiusalass) và tìm hiểu hàm `numpy.linalg.cholesky` trong Python. Áp dụng để giải hệ phương trình sau đối với vế phải b lần lượt bằng $[2, 3, 0]^T$ và $[2, 5, -2]^T$

\begin{align*}
    4x_1 + -2x_2 + 4x_3 &= b_1 \\
    -2x_1 + 5x_2 - 4x_3 &= b_2 \\
    4x_1 + -4x_2 + 6x_3 &= b_3
\end{align*}

In [ ]:
# Initialize matrix and vector
A = [[4, -2, 4], [-2, 5, -4], [4, -4, 6]]
A = np.array(A)
b1 = [2, 3, 0]
b2 = [2, 5, -2]

# Decomposition using cholesky method
L = np.linalg.cholesky(A)

# Implement function for solving algebric equation
def solve(L, b):
    """
    Args:
        L: a lower triangle matrix is decomposited using cholesky method
        b: a vector
    Return:
        Solution of Ax = b, where A = L * L.T
    """    
    n = len(L)
    
    # Solve Ly=b
    for idx in range(0, n):
        b[idx] = (b[idx] - np.dot(L[idx, 0:idx], b[0:idx])) / L[idx, idx]
    
    # Solve L.Tx = y
    LT = L.T
    b[n-1] = b[n-1] / U[n-1, n-1]
    for idx in range(n-2, -1, -1):
        b[idx] = (b[idx] - np.dot(LT[idx, idx+1:n], b[idx+1 : n])) / LT[idx, idx]
    
    return b

# Using implemented function for solving
x = solve(L, b1)
y = solve(L, b2)
print(f"x = {x} \ny = {y}")

x = [1.0, 1.0, 0.0] 
y = [2.0, 1.0, -1.0]


In [ ]:
# Using library to solve

b1 = [2, 3, 0]
b2 = [2, 5, -2]

x = np.linalg.solve(A, b1)
y= np.linalg.solve(A, b2)
print(f"x = {x} \ny = {y}")

x = [1. 1. 0.] 
y = [ 2.  1. -1.]
