# Câu 1:

Với tham số t, sử dụng toolbox linalg hãy đi tìm chuẩn 1,2, vô cùng của ma trận A = [[1, t] , [t, t^2+1]] với t = 10,100,200,...,1000.Tìm số điều kiện của các ma trận A đó

In [1]:
from numpy import linalg as LA
import numpy as np
value = np.array([10,100,200,300,400,500,600,700,800,900,1000])
for t in value:
    A = np.array([[1,t],[t,1+t**2]])
    print("Với t = ",t)
    print("Chuẩn p = 1 của matrix A",LA.norm(A,1))
    print("Số điều kiện theo chuẩn p = 1 của matrix A"+str(LA.cond(A,1))+"\n")
    print("Chuẩn p = 2 của matrix A",LA.norm(A))
    print("Số điều kiện theo chuẩn p = 2 của matrix A"+str(LA.cond(A,2))+"\n")
    print('Chuẩn p = ∞ của matrix A',LA.norm(A,np.inf))
    print('Số điều kiện theo chuẩn p = ∞ của matrix A'+str(LA.cond(A,np.inf))+"\n")



Với t =  10
Chuẩn p = 1 của matrix A 111.0
Số điều kiện theo chuẩn p = 1 của matrix A12320.999999999827

Chuẩn p = 2 của matrix A 101.99019560722492
Số điều kiện theo chuẩn p = 2 của matrix A10401.999903865906

Chuẩn p = ∞ của matrix A 111.0
Số điều kiện theo chuẩn p = ∞ của matrix A12320.999999999827

Với t =  100
Chuẩn p = 1 của matrix A 10101.0
Số điều kiện theo chuẩn p = 1 của matrix A102030200.9999478

Chuẩn p = 2 của matrix A 10001.999900019995
Số điều kiện theo chuẩn p = 2 của matrix A100040002.01832864

Chuẩn p = ∞ của matrix A 10101.0
Số điều kiện theo chuẩn p = ∞ của matrix A102030200.9999478

Với t =  200
Chuẩn p = 1 của matrix A 40201.0
Số điều kiện theo chuẩn p = 1 của matrix A1616120401.0014699

Chuẩn p = 2 của matrix A 40001.99997500125
Số điều kiện theo chuẩn p = 2 của matrix A1600159998.9022539

Chuẩn p = ∞ của matrix A 40201.0
Số điều kiện theo chuẩn p = ∞ của matrix A1616120401.0014699

Với t =  300
Chuẩn p = 1 của matrix A 90301.0
Số điều kiện theo chuẩn p = 1 của m

# Câu 2:

Ma trận Hermit được định nghĩa bởi Hn = [ 1 / i+j-1] với  i, j = 1 tới n. 
Hãy đi tìm số điều kiện của H5, H12 theo các chuẩn 1, 2, ∞.

In [ ]:
from numpy import linalg as LA
import numpy as np

# cách 1: from scipy.linalg import hilbert
# cách 2: hàm nhập ma trận
 
def inputmatrix(n):
    a = []
    for i in range(1,n+1):
        for j in range(1,n+1):
            ele = 1/(i+j-1)
            a.append(ele)
    b = np.reshape(a,(n,n))
    return b
def result(A):
    print('Số điều kiện của ma trận theo chuẩn p = 1 là:', LA.cond(A,1))
    print('Số điều kiện của ma trận theo chuẩn p = 2 là:', LA.cond(A))
    print('Số điều kiện của ma trận theo chuẩn p = ∞ là:', LA.cond(A,np.inf))
    
# nhập ma trận H5
print('Ma trận H5 là:'+"\n")
print(inputmatrix(5))
print('Số điều kiện của H5 theo các chuẩn:' +'\n')
result(inputmatrix(5))

# nhập ma trận H12
print('Ma trận H12 là:'+"\n")
print( inputmatrix(12))
print('Số điều kiện của H12 theo các chuẩn:' +'\n')
result(inputmatrix(12))



Ma trận H5 là:

[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
Số điều kiện của H5 theo các chuẩn:

Số điều kiện của ma trận theo chuẩn p = 1 là: 943655.9999992527
Số điều kiện của ma trận theo chuẩn p = 2 là: 476607.25024100044
Số điều kiện của ma trận theo chuẩn p = ∞ là: 943655.9999992514
Ma trận H12 là:

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857]
 [0.25       0.2        0.16666667 0.142

# Câu 3: Phân tích LU

### Thực hành:      
Viết hàm trong Python để tìm phân tích A = LU và giải hệ phương trình
Ax = b ở trên. So sánh kết quả của các em với cách giải sử dụng toolbox linalg trong Python.

                            2x1 + 4x2 + 3x3 = 3
                            3x1 + x2 − 2x3 = 3
                            4x1 + 11x2 + 7x3 = 4

In [ ]:
import numpy as np
A = np.array([[2,4,3],[3,1,-2],[4,11,7]])
# đổi A sang matrix gồm các giá trị kiểu float(tránh bị làm tròn số)
A = A.astype(float)
b = np.array([3.,3.,4.])
#sử dụng toolbox
x1 = np.linalg.solve(A,b)
print('Nghiệm của hệ của phương trình sử dụng toolbox là:',x1)
# thuật toán tự viết
def LU(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)
    for i in range(n):
        p = U[i,i]
        for j in range(i+1,n):
            L[j,i] = U[j,i]/p
            U[j] = U[j] - L[j,i]*U[i]
            b[j] = b[j] - L[j,i] * b[i]
    return L,U,b

print('Kết quả phân tích LU là:')
L,U,b = LU(A)
print('Ma trận L là:'+"\n")
print(str(L) +"\n")
print('Ma trận U là:'+"\n")
print(U)
def solution(U,b):
    n = U.shape[0]
    x = np.copy(b)
    x[n-1] = b[n-1]/U[(n-1),(n-1)]
    for i in range(n-2,-1,-1):
        sum = 0
        for j in range(n-1,i,-1):
            sum += x[j]*U[i,j]
        x[i] = (b[i] - sum)/U[i,i]
    return x
x = solution(U,b)
print('Nghiệm x giải bằng thuật toán:',x)


Nghiệm của hệ của phương trình sử dụng toolbox là: [ 2. -1.  1.]
Kết quả phân tích LU là:
Ma trận L là:

[[ 1.   0.   0. ]
 [ 1.5  1.   0. ]
 [ 2.  -0.6  1. ]]

Ma trận U là:

[[ 2.   4.   3. ]
 [ 0.  -5.  -6.5]
 [ 0.   0.  -2.9]]
Nghiệm x giải bằng thuật toán: [ 2. -1.  1.]


# Câu 4: Phân tích PLU

### Thực hành:

Viết hàm trong Python để tìm phân tích P LU của ma trận A và giải hệ phương trình Ax = b ở trên. So sánh kết quả của các em với cách giải sử dụng toolbox linalg trong Python.

                                x2           = b1,
                           2x1     + x3      = b2,
                               2x2      + x4 = b3,
                                    2x3      = b4.

In [2]:
from scipy import linalg as LA
import numpy as np
A = np.array([[0,1,0,0],[2,0,1,0],[0,2,0,1],[0,0,2,0]])
b = np.array([1,2,3,4])
print("A is: \n", A)
print("b is: \n", b)

# sử dụng toolbox
p,l,u = LA.lu(A)
print("Ma trận P,L,U của A là:")
print(p)
print(l)
print(u)
x = np.linalg.solve(A,b)
print('Nghiệm của hệ phương trình là:',x)

A is: 
 [[0 1 0 0]
 [2 0 1 0]
 [0 2 0 1]
 [0 0 2 0]]
b is: 
 [1 2 3 4]
Ma trận P,L,U của A là:
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.5 0.  1. ]]
[[ 2.   0.   1.   0. ]
 [ 0.   2.   0.   1. ]
 [ 0.   0.   2.   0. ]
 [ 0.   0.   0.  -0.5]]
Nghiệm của hệ phương trình là: [0. 1. 2. 1.]


# Câu 5: Phân tích LU và PLU của Pascal, Leslie và Vander Monde

Tìm hiểu các ma trận Pascal, Leslie và Vander Monde trong module scipy.linalg. Tìm các phân tích LU và PLU của chúng, ứng với các ma trận cỡ 3 × 3 hoặc 4 × 4.

In [ ]:
from scipy import linalg as LA
from numpy import vander
a = LA.pascal(3) 
b = LA.leslie([2,3,2],[7,9])
c = vander([3,4,2],increasing = True) # các cột giá trị tăng theo số mũ: cột 1 mũ 0, cột 2 mũ 1, cột 3 mũ 2
# in ma trận
print('Ma trận pascal cỡ 3x3 là:')
print(a)
print('Ma trận leslie cỡ 3x3 là:')
print(b)
print('Ma trận Vander Monde cỡ 3x3 là:')
print(c)
def LU(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)
    for i in range(n):
        p = U[i,i]
        for j in range(i+1,n):
            L[j,i] = U[j,i]/p
            U[j] = U[j] - L[j,i]*U[i]
    return L,U
# phân tích LU
Lp,Up = LU(a)
print('Ma trận L,U của Pascal là:')
print(Lp)
print(Up)

Ll,Ul = LU(b)
print('Ma trận L,U của Leslie là:')
print(Ll)
print(Ul)

Lv,Uv = LU(c)
print('Ma trận L,U của Vander Monde là:')
print(Lv)
print(Uv)

# phân tích P,L,U
p1,l1,u1 = LA.lu(a)
print('Ma trận P,L,U của Pascal là:')
print(p1)
print(l1)
print(u1)

p2,l2,u2 = LA.lu(b)
print('Ma trận P,L,U của Leslie là:')
print(p2)
print(l2)
print(u2)

p3,l3,u3 = LA.lu(c)
print('Ma trận P,L,U của Vander Monde là:')
print(p3)
print(l3)
print(u3)

Ma trận pascal cỡ 3x3 là:
[[1 1 1]
 [1 2 3]
 [1 3 6]]
Ma trận leslie cỡ 3x3 là:
[[2 3 2]
 [7 0 0]
 [0 9 0]]
Ma trận Vander Monde cỡ 3x3 là:
[[ 1  3  9]
 [ 1  4 16]
 [ 1  2  4]]
Ma trận L,U của Pascal là:
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 2. 1.]]
[[1 1 1]
 [0 1 2]
 [0 0 1]]
Ma trận L,U của Leslie là:
[[ 1.   0.   0. ]
 [ 3.5  1.   0. ]
 [ 0.  -0.9  1. ]]
[[  2   3   2]
 [  0 -10  -7]
 [  0   0  -6]]
Ma trận L,U của Vander Monde là:
[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 1. -1.  1.]]
[[1 3 9]
 [0 1 7]
 [0 0 2]]
Ma trận P,L,U của Pascal là:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1.  0.  0. ]
 [1.  1.  0. ]
 [1.  0.5 1. ]]
[[ 1.   1.   1. ]
 [ 0.   2.   5. ]
 [ 0.   0.  -0.5]]
Ma trận P,L,U của Leslie là:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.28571429 0.33333333 1.        ]]
[[7. 0. 0.]
 [0. 9. 0.]
 [0. 0. 2.]]
Ma trận P,L,U của Vander Monde là:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 1. -1.  1.]]

# CÂU 6: Giải hệ bằng PLU

Tìm các phân tích PLU của các ma trận A dưới đây và giải hệ phương trình vi phân tương ứng, với b là random vector, làm tròn 4 chữ số thập phân khi tính toán bằng tay.

#### Phần i:

                                 A1 =[[ 4 −1 −2],
                                     [−1 4 −1],
                                     [−1 −2 4] ]

In [ ]:
from scipy import linalg as LA
import numpy as np
A1 = np.array([[4,-1,-2],[-1,4,-1],[-1,-2,4]])
# phân tích PLU
p1,l1,u1 = LA.lu(A1)
print('Ma trận P,L,U của A1 là:')
print(p1)
print(l1)
print(u1)
b1 = np.random.randint(1,9,size = 3)
print('Random vecto b là: ')
print(b1)
x1 = np.linalg.solve(A1,b1)
print('Nghiệm của hệ phương trình là:',x1)

Ma trận P,L,U của A1 là:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [-0.25 -0.6   1.  ]]
[[ 4.   -1.   -2.  ]
 [ 0.    3.75 -1.5 ]
 [ 0.    0.    2.6 ]]
Random vecto b là: 
[7 2 4]
Nghiệm của hệ phương trình là: [3.84615385 2.23076923 3.07692308]


#### Phần ii:

                            
                            A2 = [[−3 1 −1],
                                  [−1 4 1],
                                  [2 −1 6]]



In [ ]:
A2 = np.array([[-3,1,-1],[-1,4,1],[2,-1,6]])
p2,l2,u2 = LA.lu(A2)
print('Ma trận P,L,U của A2 là:')
print(p2)
print(l2)
print(u2)
b2 = np.random.randint(1,9,size = 3)
print('Random vecto b là: ')
print(b2)
x2 = np.linalg.solve(A2,b2)
print('Nghiệm của hệ phương trình là:',x2)

Ma trận P,L,U của A2 là:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [-0.66666667 -0.09090909  1.        ]]
[[-3.          1.         -1.        ]
 [ 0.          3.66666667  1.33333333]
 [ 0.          0.          5.45454545]]
Random vecto b là: 
[8 5 4]
Nghiệm của hệ phương trình là: [-3.25000000e+00  7.56970244e-17  1.75000000e+00]


#### Phần iii:

                            
                            A3 =[[ 0 1 0 0],
                                [ 2 0 1 0],
                                [ 0 2 0 1],
                                [ 0 0 2 0]]

In [ ]:
A3 = np.array([[0,1,0,0],[2,0,1,0],[0,2,0,1],[0,0,2,0]])
p3,l3,u3 = LA.lu(A3)
print('Ma trận P,L,U của A2 là:')
print(p3)
print(l3)
print(u3)
b3 = np.random.randint(1,9,size = 4)
print('Random vecto b là: ')
print(b3)
x3 = np.linalg.solve(A3,b3)
print('Nghiệm của hệ phương trình là:',x3)

Ma trận P,L,U của A2 là:
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.5 0.  1. ]]
[[ 2.   0.   1.   0. ]
 [ 0.   2.   0.   1. ]
 [ 0.   0.   2.   0. ]
 [ 0.   0.   0.  -0.5]]
Random vecto b là: 
[8 1 5 8]
Nghiệm của hệ phương trình là: [ -1.5   8.    4.  -11. ]


#### Phần iv:

                      A4 =  [ [2 2 0 0],
                              [2 2 1 0],
                              [1 1 0 2],
                              [0 1 0 0] ]

In [ ]:
A4 = np.array([[2,2,0,0],[2,2,1,0],[1,1,0,2],[0,1,0,0]])
p4,l4,u4 = LA.lu(A4)
print('Ma trận P,L,U của A2 là:')
print(p4)
print(l4)
print(u4)
b4 = np.random.randint(1,9,size = 4)
print('Random vecto b là: ')
print(b4)
x4 = np.linalg.solve(A4,b4)
print('Nghiệm của hệ phương trình là:',x4)

Ma trận P,L,U của A2 là:
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
[[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [1.  0.  1.  0. ]
 [0.5 0.  0.  1. ]]
[[2. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 2.]]
Random vecto b là: 
[3 1 4 5]
Nghiệm của hệ phương trình là: [-3.5   5.   -2.    1.25]


# Câu 7: Phân tích Cholesky

Trong trường hợp ma trận A là đối xứng, xác định dương thì phương pháp Cholesky thường được sử dụng. Hãy đọc phương pháp này trang 116-120 (Giáo trình ĐHBK) hoặc Section 2.4 (Giáo trình Kiusalass) và tìm hiểu hàm numpy.linalg.cholesky trong Python. Áp
dụng để giải hệ phương trình sau đối với vế phải b lần lượt bằng [2 3 0]T và [2 5 − 2]T

                        4x1 − 2x2 + 4x3 = b1
                        −2x1 + 5x2 − 4x3 = b2
                        4x1 − 4x2 + 6x3 = b3

In [ ]:
from numpy.linalg import cholesky
import numpy as np
A = np.array([[4,-2,4],[-2,5,-4],[4,-4,6]])
b1 = np.array([2,3,0])
b2 = np.array([2,5,-2])
# hàm tìm nghiệm bằng phương pháp phân tích cholesky
def choleskySol(A,b):
    n = len(b)
    #solution of [l]{y} = b
    for k in range(n):
        b[k] = (b[k] - np.dot(L[k,0:k],b[0:k])) / L[k,k]
    #solution of [L_transpose]{x} = {y}
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(L[k+1:n,k],b[k+1:n]))/L[k,k]
    return b
L = np.linalg.cholesky(A)
print('Ma trận L sau khi phân tích cholesky:')
print(L)

print('Nghiệm của hệ phương trình với b = [2,3,0] là:')
x1 = choleskySol(L,b1)
print(x1)
print('Nghiệm của hệ phương trình với b = [2,5,-2] là:')
x2 = choleskySol(L,b1)
print(x2)

Ma trận L sau khi phân tích cholesky:
[[ 2.  0.  0.]
 [-1.  2.  0.]
 [ 2. -1.  1.]]
Nghiệm của hệ phương trình với b = [2,3,0] là:
[1 1 0]
Nghiệm của hệ phương trình với b = [2,5,-2] là:
[0 0 0]
