In [6]:
from numpy import array
import numpy.linalg as la

A = array([[1, 2, 3],[4, 5, 6],[7, 8, 0]])
#la.norm(A,1)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [23]:
from scipy.linalg import lu
from numpy import array

A = array([[10,-1,2,-3],[1,10,-1,2],[2,3,20,-1],[3,2,1,20]])
print(A)

P, L, U = lu(A)
print("Ma tran P")
print(P)
print("Ma tran L")
print(L)
print("Ma tran U")
print(U)

#print(P*L*U - A)   # Matlab thi duoc, Python thi 0
print(dot(P,dot(L,U)) - A) # Dung trong Python

[[10 -1  2 -3]
 [ 1 10 -1  2]
 [ 2  3 20 -1]
 [ 3  2  1 20]]
Ma tran P
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Ma tran L
[[1.         0.         0.         0.        ]
 [0.1        1.         0.         0.        ]
 [0.2        0.31683168 1.         0.        ]
 [0.3        0.22772277 0.03369673 1.        ]]
Ma tran U
[[10.         -1.          2.         -3.        ]
 [ 0.         10.1        -1.2         2.3       ]
 [ 0.          0.         19.98019802 -1.12871287]
 [ 0.          0.          0.         20.41427156]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  4.44089210e-16  0.00000000e+00  0.00000000e+00]
 [ 4.44089210e-16 -2.22044605e-16  0.00000000e+00  0.00000000e+00]]


In [20]:
L, U = lu(A,True)

print(L)
print(U)

from numpy import dot
dot(L,U)-A

[[0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]
 [1.         0.         0.        ]]
[[7.         8.         0.        ]
 [0.         0.85714286 3.        ]
 [0.         0.         4.5       ]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
P = array([[0,0,1],[1,0,0],[0,1,0]])
L = array([[1,0,0],[0.5,1,0],[1/3.,1/4.,1]])
U = array([[2,3,1],[0,1,2],[0,0,2]])
print(P)
print(L)
print(U)


[[0 0 1]
 [1 0 0]
 [0 1 0]]
[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.33333333 0.25       1.        ]]
[[2 3 1]
 [0 1 2]
 [0 0 2]]


In [30]:
A = dot(P,dot(L,U))
print("A la")
print(A)

b = array([1,2,3])
print("b la")
print(b)

A la
[[0.66666667 1.25       2.83333333]
 [2.         3.         1.        ]
 [1.         2.5        2.5       ]]
b la
[1 2 3]


In [35]:
A = array([[1,1],[1,-1],[2,1]])
print(A)
b = array([2,0,4])
print(b)

[[ 1  1]
 [ 1 -1]
 [ 2  1]]
[2 0 4]


In [39]:
print("Cach 1: phuong trinh chinh tac")
M = dot(A.T,A)
print(M)
n = dot(A.T,b)
print(n)
from numpy.linalg import solve


Cach 1: phuong trinh chinh tac
[[6 2]
 [2 3]]
[10  6]
[1.28571429 1.14285714]


In [52]:
print("Cach 2: su dung phan tich QR")
from scipy.linalg import qr
Q,R = qr(A)
#print(Q)
#print(R)
#print(dot(Q,R)-A)

Q1 = Q[:,0:2]
R1 = R[0:2,:]
print(Q1)
print(R1)
print(dot(Q1,R1)-A)

p = dot(Q1.T,b)
print(p)

from numpy.linalg import solve
x = solve(R1,p)
print(x)

Cach 2: su dung phan tich QR
[[-0.40824829  0.43643578]
 [-0.40824829 -0.87287156]
 [-0.81649658  0.21821789]]
[[-2.44948974 -0.81649658]
 [ 0.          1.52752523]]
[[2.22044605e-16 4.44089210e-16]
 [0.00000000e+00 2.22044605e-16]
 [0.00000000e+00 2.22044605e-16]]
[-4.0824829   1.74574312]
[1.28571429 1.14285714]


In [6]:
from numpy import array, dot
import numpy.linalg as la

A = array([[3,1, 1],[1, 5, 2],[1, 8, 10]])

b = array([5,8,19])

P =  array([[3, 0, 0],[0, 5, 0],[0, 0, 10]])
N = A - P
ivP = inv(P)
x0 = array([0,0,0]); xold = x0;

for i in range(1,100):
    xnew = inv(P) * (-N*xold+b)
    
print(xnew)


ImportError: cannot import name 'inv' from 'numpy' (C:\Users\phiha\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py)